// Build-time step: flatten each entry .wgsl (and its import graph, including
// @vgpu/wgsl-std) into one plain WGSL string, emitted as a static ES module.
//
// This is what keeps the portfolio a zero-build static site: the WGSL module
// graph is resolved here, on the developer machine, so the browser only ever
// sees finished strings handed straight to vgpu's effect(gpu, source).
//
//   node build-shaders.mjs

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolveShader } from "@vgpu/wgsl/runtime";

// The five effects pipeline.js constructs. gbuffer/geodesic/disk/stars are not
// listed: they are imported by these entries and get inlined by the resolver.
const ENTRIES = ["bake", "refine", "shade", "bloom", "composite"];

const chunks = [];

for (const name of ENTRIES) {
  const entry = fileURLToPath(new URL(`./${name}.wgsl`, import.meta.url));
  const resolved = await resolveShader({ entry });
  const deps = resolved.deps?.length ?? 0;
  console.log(
    `${name}.wgsl -> ${resolved.wgsl.length} chars (${deps} dep${deps === 1 ? "" : "s"} inlined)`
  );
  chunks.push(`export const ${name}Wgsl = ${JSON.stringify(resolved.wgsl)};`);
}

const banner = `// GENERATED by build-shaders.mjs - do not edit.
// Flattened WGSL for the vgpu "optimized-black-hole" example.
`;

const outPath = fileURLToPath(new URL("./shaders.generated.mjs", import.meta.url));
writeFileSync(outPath, `${banner}\n${chunks.join("\n\n")}\n`);
console.log(`\nwrote ${outPath}`);
